(function() {
    'use strict';

    window.countryList = {
        ru: {
            name: 'Россия',
            code: 'ru',
            price: 990,
            oldPrice: 1980,
            labelPrice: 'руб.',
            phoneHelper: 'Например +7 9031234567',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            countryError: 'Страна обязательна для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            isDefault: true,
            cityCurrentHelper: 'Москва',
            cityRandomHelper: ['Москва', 'Санкт-Петербург', 'Новосибирск', 'Екатеринбург', 'Нижний Новгород', 'Казань', 'Самара'],
            nameRandomMaleHelper: ['Дмитрий Бирюков', 'Гавриил Силин', 'Никита Трофимов'],
            nameRandomFemaleHelper: ['Алиса Степанова', 'Виктория Шарова', 'Валерия Агафонова', 'Лариса Киселёва'],
            dollarEquivalent: '46 руб',
        },
        at: {
            name: 'Австрия',
            code: 'at',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +43 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Вена',
            cityRandomHelper: ['Вена', 'Лаутерах', 'Санкт-Андре', 'Кёфлах', 'Имст', 'Юденбург', 'Глайсдорф'],
            nameRandomMaleHelper: ['Франц Грубер', 'Йозеф Хубер', 'Йоханн Вагнер', 'Карл Мюллер'],
            nameRandomFemaleHelper: ['Хельга Пихлер', 'Моника Мейер', 'Сабина Хофер'],
            dollarEquivalent: '0,8 евро',
        },
        az: {
            name: 'Азербайджан',
            code: 'az',
            price: 39,
            oldPrice: 79,
            labelPrice: 'манат',
            phoneHelper: 'Например +994 123456789',
            nameHelper: 'Захра Мамедова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Агдам',
            cityRandomHelper: ['Агдам', 'Агдере', 'Джебраил', 'Зангелан', 'Кельбаджар', 'Лачин', 'Физули'],
            nameRandomMaleHelper: ['Аббас Мамедов', 'Исмаилбек Аскеров', 'Данияр Алиев'],
            nameRandomFemaleHelper: ['Адия Гамбарова', 'Луиза Вагифова', 'Лязат Мехтиева', 'Махпула Джафарова'],
            dollarEquivalent: '1,5 манат',
        },
        am: {
            name: 'Армения',
            code: 'am',
            price: 13990,
            oldPrice: 27980,
            labelPrice: 'дрм',
            phoneHelper: 'Например +374 123456789',
            nameHelper: 'Мари Абитян',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Арагацотн',
            cityRandomHelper: ['Арагацотн', 'Котайк', 'Лори', 'Сюник', 'Арарат', 'Армавир', 'Вайоц Дзор', 'Гегаркуник'],
            nameRandomMaleHelper: ['Агаси Абитян', 'Вахак Айтруни', 'Гагик Баласакан', 'Давид Ваануни'],
            nameRandomFemaleHelper: ['Арусь Габелуни', 'Егине Баласакан', 'Наира Едесян', 'Меланья Зарехаванян'],
            dollarEquivalent: '433 дрм',
        },
        by: {
            name: 'Беларусь',
            code: 'by',
            price: 39,
            oldPrice: 78,
            labelPrice: 'руб.',
            phoneHelper: 'Например +375 123456789',
            nameHelper: 'Маргарыта Концява',
            nameError: 'Імя абавязковы для запаўнення',
            phoneError: 'Тэлефон абавязковы для запаўнення',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Краіна абавязковы для запаўнення',
            cityCurrentHelper: 'Минск',
            cityRandomHelper: ['Минск', 'Бобруйск', 'Витебск', 'Могилёв', 'Полоцк', 'Рогачёв', 'Гомель'],
            nameRandomMaleHelper: ['Адам Зинкевич', 'Олег Филипенко', 'Елисей Скворцов'],
            nameRandomFemaleHelper: ['Елена Полищук', 'Анна Высоцкая', 'Барбара Смолякова', 'Белла Ковальчукова'],
            dollarEquivalent: '1,68 руб',
        },
        be: {
            name: 'Бельгия',
            code: 'be',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +32 1234567890',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            countryError: 'Страна обязательна для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            cityCurrentHelper: 'Борглон',
            cityRandomHelper: ['Борглон', 'Дюрбюи', 'Спа', 'Ньивпорт', 'Дамме', 'Намюр', 'Гистел', 'Виртон'],
            nameRandomMaleHelper: ['Адам Диалло', 'Мохаммад Бах', 'Раян Янсенс', 'Габриель Питерс'],
            nameRandomFemaleHelper: ['Ясмин Нгуйен', 'Лина Барри', 'Сара Мартинс', 'Луиза Дюбуа'],
            dollarEquivalent: '0,8 евро',
        },
        bg: {
            name: 'Болгария',
            code: 'bg',
            price: 59,
            oldPrice: 118,
            labelPrice: 'лев',
            phoneHelper: 'Например +359 123456789',
            nameHelper: 'Мария Агова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'София',
            cityRandomHelper: ['София', 'Пловдив', 'Варна', 'Бургас', 'Русе', 'Стара-Загора', 'Плевен'],
            nameRandomMaleHelper: ['Жеко Велев', 'Станислав Даскалов', 'Галин Гочев'],
            nameRandomFemaleHelper: ['Стефка Минева', 'Александра Пенчева', 'Кристина Жекова', 'Руска Хинкова'],
            dollarEquivalent: '1,56 лев',
        },
		gb: {
            name: 'Великобритания',
            code: 'gb',
            price: 39,
            oldPrice: 78,
            labelPrice: 'фунт',
            phoneHelper: 'Например +44 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Лондон',
            cityRandomHelper: ['Лондон', 'Лидс', 'Шеффилд', 'Манчестер', 'Ливерпуль', 'Бристоль', 'Ковентри'],
            nameRandomMaleHelper: ['Этан Френч', 'Элмер Карр', 'Хэролд Армстронг', 'Максимиллиан Маккензи'],
            nameRandomFemaleHelper: ['Джоанна Уолш', 'Моника Уэбб', 'Мэдисон Паркс'],
            dollarEquivalent: '0,69 фунт',
        },
        hu: {
            name: 'Венгрия',
            code: 'hu',
            price: 8900,
            oldPrice: 17800,
            labelPrice: 'фор',
            phoneHelper: 'Например +36 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Будапешт',
            cityRandomHelper: ['Будапешт', 'Дунауйварош', 'Эрд', 'Веспрем', 'Залаэгерсег', 'Эгер', 'Надьканижа'],
            nameRandomMaleHelper: ['Элек Ковач', 'Тибор Балла', 'Карой Галаш'],
            nameRandomFemaleHelper: ['Аурель Мадьяр', 'Гизелла Такач', 'Лаура Бакош', 'Лилла Немеш'],
            dollarEquivalent: '246 фор',
        },
        de: {
            name: 'Германия',
            code: 'de',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +490 123456789',
            nameHelper: 'Ханна Беккер',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Берлин',
            cityRandomHelper: ['Берлин', 'Гамбург', 'Мюнхен', 'Кёльн', 'Штутгарт', 'Дюссельдорф', 'Дортмунд'],
            nameRandomMaleHelper: ['Райнер Бём', 'Йенс Ауттенберг', 'Аксель Циглер', 'Симон Тидеман'],
            nameRandomFemaleHelper: ['Сара Герстле', 'Ирма Зимен', 'Рената Кляйн'],
            dollarEquivalent: '0,8 евро',
        },
        gr: {
            name: 'Греция',
            code: 'gr',
            price: 29,
            oldPrice: 58,
            labelPrice: 'евро',
            phoneHelper: 'Например +30 0123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Афины',
            cityRandomHelper: ['Афины', 'Салоники', 'Патры', 'Ираклион', 'Лариса', 'Волос', 'Ахарнес'],
            nameRandomMaleHelper: ['Агазон Галифианаксис', 'Адрастос Аматанидис', 'Байон Ксенакис', 'Влазис Спанидис'],
            nameRandomFemaleHelper: ['Агата Заробала', 'Барбара Цавахиду', 'Дайона Сифакису'],
            dollarEquivalent: '0,8 евро',
        },
        ge: {
            name: 'Грузия',
            code: 'ge',
            price: 49,
            oldPrice: 99,
            labelPrice: 'лари',
            phoneHelper: 'Например +995 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Тбилиси',
            cityRandomHelper: ['Тбилиси', 'Кутаиси', 'Рустави', 'Батуми', 'Гори', 'Поти', 'Зугдиди'],
            nameRandomMaleHelper: ['Георги Беридзе', 'Давити Капанадзе', 'Зураби Мамедов', 'Левани Гелашвили'],
            nameRandomFemaleHelper: ['Тамари Гогниашвили', 'Нино Гуладзе', 'Мариами Дудучава'],
            dollarEquivalent: '2,2 лари',
        },
		il: {
            name: 'Израиль',
            code: 'il',
            price: 60,
            oldPrice: 120,
            labelPrice: 'шекель',
            phoneHelper: 'Например +972 12345678',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Иерусалим',
            cityRandomHelper: ['Иерусалим', 'Тель-Авив', 'Хайфа', 'Ришон-ле-Цион', 'Петах-Тиква', 'Ашдод', 'Нетания'],
            nameRandomMaleHelper: ['Аарон Штерн', 'Абба Цвейг', 'Берел Блюм', 'Гавриэль Арье'],
            nameRandomFemaleHelper: ['Адина Дов', 'Бина Вайс', 'Далья Йоффе'],
            dollarEquivalent: false,
        },
        es: {
            name: 'Испания',
            code: 'es',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +34 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Мадрид',
            cityRandomHelper: ['Мадрид', 'Барселона', 'Валенсия', 'Севилья', 'Сарагоса', 'Малага', 'Мурсия'],
            nameRandomMaleHelper: ['Педро Франко', 'Энрике Ортега', 'Артуро Кампос'],
            nameRandomFemaleHelper: ['Лорена Суньига', 'Милагрос Вальдес', 'Моника Нуньес', 'Сандра Бласкес'],
            dollarEquivalent: '0,8 евро',
        },
        it: {
            name: 'Италия',
            code: 'it',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +39 1234567890',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Рим',
            cityRandomHelper: ['Рим', 'Милан', 'Неаполь', 'Турин', 'Палермо', 'Генуя', 'Болонья'],
            nameRandomMaleHelper: ['Лука Пицци', 'Изидоро Лоренци', 'Даниэле Паскуале', 'Дамиано Белли'],
            nameRandomFemaleHelper: ['Кончетта Бенедетти', 'Томмаза Коррадини', 'Карла Бернарди'],
            dollarEquivalent: '0,8 евро',
        },
        kz: {
            name: 'Казахстан',
            code: 'kz',
            price: 5390,
            oldPrice: 11000,
            labelPrice: 'тг.',
            phoneHelper: 'Например +77 123456789',
            nameHelper: 'Айжаксым Омарова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Алма-Ата',
            cityRandomHelper: ['Алма-Ата', 'Шымкент', 'Астана', 'Караганда', 'Актобе', 'Тараз', 'Павлодар'],
            nameRandomMaleHelper: ['Абай Абдильдин', 'Абылай Валиханов', 'Гавит Габдуллин', 'Кадыр Джандосов'],
            nameRandomFemaleHelper: ['Агипа Ертаева', 'Данеля Жубанова', 'Табия Ибрагимова'],
            dollarEquivalent: '279 тг',
        },
        cy: {
            name: 'Кипр',
            code: 'cy',
            price: 29,
            oldPrice: 58,
            labelPrice: 'евро',
            phoneHelper: 'Например +357 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Лимасол',
            cityRandomHelper: ['Лимасол', 'Строволос', 'Никосия', 'Ларнака', 'Лакатамия', 'Пафос', 'Като Полемидия'],
            nameRandomMaleHelper: ['Alireza Spyrou', 'Inanç Constantinou', 'Jan Adamou', 'Kemal Kyriakou', 'Stefanos Pavlou'],
            nameRandomFemaleHelper: ['Agnieszka Ioannou', 'Doris Christou', 'Eleni Antoniou', 'Georgia Demitriou', 'Hwa-Young Markou'],
            dollarEquivalent: '0,8 евро',
        },
        kg: {
            name: 'Киргизия',
            code: 'kg',
            price: 1990,
            oldPrice: 3990,
            labelPrice: 'сом',
            phoneHelper: 'Например +996 123456789',
            nameHelper: 'Жазгуль Кирдякова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Бишкек',
            cityRandomHelper: ['Бишкек', 'Ош', 'Джалал-Абад', 'Каракол', 'Токмок', 'Узген', 'Кара-Балта'],
            nameRandomMaleHelper: ['Абдуразак Абдурасулов', 'Даниель Абилдае', 'Илимбек Исмаилов', 'Кулжигит Забара'],
            nameRandomFemaleHelper: ['Азиза Касиева', 'Гулай Феликс', 'Дамира Лобода'],
            dollarEquivalent: '61 сом',
        },
        lv: {
            name: 'Латвия',
            code: 'lv',
            price: 24,
            oldPrice: 48,
            labelPrice: 'евро',
            phoneHelper: 'Например +371 123456789',
            nameHelper: 'Санита Берзиньш',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Рига',
            cityRandomHelper: ['Рига', 'Даугавпилс', 'Лиепая', 'Елгава', 'Юрмала', 'Вентспилс', 'Резекне'],
            nameRandomMaleHelper: ['Роберт Берзиньш', 'Маркусс Калныньш', 'Даниэль Озолиньш', 'Адриан Янсонс'],
            nameRandomFemaleHelper: ['Эвелина Лиепиньш', 'Марта Круминьш', 'Эмилия Эглитис'],
            dollarEquivalent: '0,8 евро',
        },
        lt: {
            name: 'Литва',
            code: 'lt',
            price: 24,
            oldPrice: 48,
            labelPrice: 'евро',
            phoneHelper: 'Например +370 123456789',
            nameHelper: 'Лайма Дауканте',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Вильнюс',
            cityRandomHelper: ['Вильнюс', 'Каунас', 'Клайпеда', 'Шяуляй', 'Панявежис', 'Алитус', 'Мариямполе'],
            nameRandomMaleHelper: ['Кестутис Петраускас', 'Гедеминас Станкявичюс', 'Радвила Жукаускас'],
            nameRandomFemaleHelper: ['Милда Янкаускаюс', 'Лайма Буткевичюте', 'Эгле Паулаускате', 'Алге Казлаускате'],
            dollarEquivalent: '0,8 евро',
        },
        lu: {
            name: 'Люксембург',
            code: 'lu',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +352 123456789',
            nameHelper: 'Лайма Дауканте',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Вианден',
            cityRandomHelper: ['Вианден', 'Дикирх', 'Дифферданж', 'Ремих', 'Эхтернах', 'Эш-сюр-Альзетт', 'Вильц'],
            nameRandomMaleHelper: ['Штефан Петерс', 'Норберт Хохберг', 'Вальтер Гроссе', 'Артур Бауман'],
            nameRandomFemaleHelper: ['Рената Бах', 'Катарина Герхардт', 'Карин Лоренц'],
            dollarEquivalent: '0,8 евро',
        },
        mk: {
            name: 'Македония',
            code: 'mk',
            price: 1990,
            oldPrice: 3990,
            labelPrice: 'денар',
            phoneHelper: 'Например +389 123456789',
            nameHelper: 'Elena Ionescu',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Афины',
            cityRandomHelper: ['Афины', 'Салоники', 'Патры', 'Ахарнес', 'Янина', 'Трикала', 'Каламата'],
            nameRandomMaleHelper: ['Алексиус Ксенакис', 'Ананий Аматанидис', 'Дайомедес Адамиди'],
            nameRandomFemaleHelper: ['Агата Заробала', 'Мирайн Иоанниди', 'Роксан Цавахиду', 'Танис Катракис'],
            dollarEquivalent: false,
        },
        md: {
            name: 'Молдавия',
            code: 'md',
            price: 599,
            oldPrice: 1200,
            labelPrice: 'лей',
            phoneHelper: 'Например +373 123456789',
            nameHelper: 'Elena Ionescu',
            nameError: 'Numele dorit pentru a umple',
            phoneError: 'Telefon necesare pentru a umple',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Țara este necesară pentru a umple',
            cityCurrentHelper: 'Бельцы',
            cityRandomHelper: ['Бельцы', 'Бричаны', 'Вулканешты', 'Дрокия', 'Калараш', 'Каушаны', 'Отачь'],
            nameRandomMaleHelper: ['Аурелиан Филипаш', 'Василе Николаеску', 'Драгош Гика', 'Космин Йонеску'],
            nameRandomFemaleHelper: ['Мария Кэпряну', 'Мариана Теодореску', 'Андра Войнеску'],
            dollarEquivalent: '16,3 лей',
        },
		nl: {
            name: 'Нидерланды',
            code: 'nl',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +31 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Амстердам',
            cityRandomHelper: ['Амстердам', 'Роттердам', 'Гаага', 'Харлем', 'Бреда', 'Амерсфорт', 'Маастрихт'],
            nameRandomMaleHelper: ['Андреас ван дер Хейден', 'Леннерт Петерс', 'Михил ван ден Велде'],
            nameRandomFemaleHelper: ['Мириам ван Дейк', 'Мартина Де Хан', 'Сесилия Ленартс', 'Элке Тиммерманс'],
            dollarEquivalent: '0,8 евро',
        },
        no: {
            name: 'Норвегия',
            code: 'no',
            price: 490,
            oldPrice: 980,
            labelPrice: 'крон',
            phoneHelper: 'Например +47 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Акерсхус',
            cityRandomHelper: ['Акерсхус', 'Берген', 'Гейло', 'Зандефиорд', 'Лейкангер', 'Олесунн', 'Ророс'],
            nameRandomMaleHelper: ['Гисле Антонсен', 'Никлас Стене', 'Туре Матисен', 'Улав Миккельсен'],
            nameRandomFemaleHelper: ['Ода Берг', 'Клара Карлсен', 'Ингунн Якобсен'],
            dollarEquivalent: '7,6 крон',
        },
        pl: {
            name: 'Польша',
            code: 'pl',
            price: 159,
            oldPrice: 318,
            labelPrice: 'злот',
            phoneHelper: 'Например +48 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Варшава',
            cityRandomHelper: ['Варшава', 'Краков', 'Гданьск', 'Катовице', 'Ченстохова', 'Забже', 'Плоцк'],
            nameRandomMaleHelper: ['Давид Дрозд', 'Богуслав Зых', 'Шимон Сковроньский'],
            nameRandomFemaleHelper: ['Магдалена Романовская', 'Дорота Ожеховская', 'Мария Куровская', 'Ирена Климек'],
            dollarEquivalent: '3,4 злот',
        },
        pt: {
            name: 'Португалия',
            code: 'pt',
            price: 49,
            oldPrice: 98,
            labelPrice: 'евро',
            phoneHelper: 'Например +351 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Авейру',
            cityRandomHelper: ['Авейру', 'Валенса', 'Гуарда', 'Лиссабон', 'Мангуалди', 'Помбал', 'Порту'],
            nameRandomMaleHelper: ['Кассиу Пейшоту Сантьягу', 'Балтазар Кандал Ленкаштри', 'Эмануэл Палья Мартинью', 'Даниэл Сампайю Авила'],
            nameRandomFemaleHelper: ['Дебора Карвалью Мальейру', 'Жулия Мендонса Мангейра', 'Мелисса Каминья Фариаш'],
            dollarEquivalent: '0,8 евро',
        },
        ro: {
            name: 'Румыния',
            code: 'ro',
            price: 149,
            oldPrice: 299,
            labelPrice: 'RON',
            phoneHelper: 'Например +40 123456789',
            nameHelper: 'Мария Ионеску',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Бухарест',
            cityRandomHelper: ['Бухарест', 'Крайова', 'Питешти', 'Ботошани', 'Тулча', 'Бряза', 'Мизил'],
            nameRandomMaleHelper: ['Василе Раду', 'Джордже Джорджеску', 'Дорел Опря'],
            nameRandomFemaleHelper: ['Наталия Маноле', 'Кэтэлина Константинеску', 'Амалия Дьякону', 'Аделина Стан'],
            dollarEquivalent: '3,7 ron',
        },
        rs: {
            name: 'Сербия',
            code: 'rs',
            price: 1590,
            oldPrice: 3180,
            labelPrice: 'динар',
            phoneHelper: 'Например +381 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Белград',
            cityRandomHelper: ['Белград', 'Заечар', 'Кралево', 'Крушевац', 'Лозница', 'Ниш', 'Панчево'],
            nameRandomMaleHelper: ['Тихомир Алексич', 'Радован Джокович', 'Миомир Рачич', 'Йосиф Шешель'],
            nameRandomFemaleHelper: ['Адрияна Белич', 'Драгана Йович', 'Миряна Зорич'],
            dollarEquivalent: '98 динар',
        },
        sk: {
            name: 'Словакия',
            code: 'sk',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +421 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Братислава',
            cityRandomHelper: ['Братислава', 'Кошице', 'Нитра', 'Прешов', 'Жилина', 'Брезно', 'Врутки'],
            nameRandomMaleHelper: ['Роман Гавличек', 'Эмил Дворжак', 'Ондржей Прокоп'],
            nameRandomFemaleHelper: ['Ива Бенешова', 'Никола Кралова', 'Габриэла Свободова', 'Ярмила Соукупова'],
            dollarEquivalent: '0,8 евро',
        },
        si: {
            name: 'Словения',
            code: 'si',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +386 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Любляна',
            cityRandomHelper: ['Любляна', 'Марибор', 'Целе', 'Крань', 'Веленье', 'Копер', 'Птуй'],
            nameRandomMaleHelper: ['Марцель Галаш', 'Янош Васс', 'Оскар Тот', 'Габор Хорват'],
            nameRandomFemaleHelper: ['Жужанна Бартане', 'Юлия Ковач', 'Александра Шоош'],
            dollarEquivalent: '0,8 евро',
        },
		tr: {
            name: 'Турция',
            code: 'tr',
            price: 149,
            oldPrice: 298,
            labelPrice: 'лир',
            phoneHelper: 'Например +90 1234567890',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Стамбул',
            cityRandomHelper: ['Стамбул', 'Анкара', 'Адана', 'Анталья', 'Малатья', 'Измит', 'Айдын'],
            nameRandomMaleHelper: ['Ахмет Шише', 'Барыш Йамур', 'Джошкунэр Джан'],
            nameRandomFemaleHelper: ['Эйлюль Катлама', 'Рабиа Гюлер', 'Фатьма Кемал', 'Эля Туран'],
            dollarEquivalent: '3,2 лир',
        },
        uz: {
            name: 'Узбекистан',
            code: 'uz',
            price: 119,
            oldPrice: 238,
            labelPrice: 'т.сум',
            phoneHelper: 'Например +998 123456789',
            nameHelper: 'Гультапчан Наркисова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Ташкент',
            cityRandomHelper: ['Ташкент', 'Самарканд', 'Наманган', 'Андижан', 'Ургенч', 'Дустабад', 'Бешарык'],
            nameRandomMaleHelper: ['Бахтиер Рашидов', 'Каримм Угланов', 'Маджид Годунов', 'Тахир Алымов'],
            nameRandomFemaleHelper: ['Адлия Наркисова', 'Гузаль Баташева', 'Нур Саидова'],
            dollarEquivalent: '3,5 т.сум',
        },
        ua: {
            name: 'Украина',
            code: 'ua',
            price: 399,
            oldPrice: 798,
            labelPrice: 'грн.',
            phoneHelper: 'Например +380 123456789',
            nameHelper: 'Анастасія Кравчук',
            nameError: 'Імя обовязково для заповнення',
            phoneError: 'Телефон обовязковий для заповнення',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Країна обовязковий для заповнення',
            cityCurrentHelper: 'Киев',
            cityRandomHelper: ['Киев', 'Харьков', 'Одесса', 'Львов', 'Винница', 'Полтава', 'Черкассы'],
            nameRandomMaleHelper: ['Альберт Коломоец', 'Борис Дзюба', 'Герасим Махно'],
            nameRandomFemaleHelper: ['Анжела Шумейко', 'Анна Семочко', 'Василиса Токар', 'Леся Щербак'],
            dollarEquivalent: '23,4 грн',
        },
        
        fr: {
            name: 'Франция',
            code: 'fr',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +33 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Париж',
            cityRandomHelper: ['Париж', 'Марсель', 'Лион', 'Тулуза', 'Ницца', 'Страсбург', 'Сент-Этьен'],
            nameRandomMaleHelper: ['Базиль Ривар', 'Флорантен Леруа', 'Сильвен Фурнье', 'Оскар Крото'],
            nameRandomFemaleHelper: ['Софи Лефевр', 'Франсина Давид', 'Стефани Лефевр'],
            dollarEquivalent: '0,8 евро',
        },
        hr: {
            name: 'Хорватия',
            code: 'hr',
            price: 299,
            oldPrice: 598,
            labelPrice: 'кун',
            phoneHelper: 'Например +385 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Загреб',
            cityRandomHelper: ['Загреб', 'Сплит', 'Риека', 'Осиек', 'Задар', 'Карловац', 'Вараждин'],
            nameRandomMaleHelper: ['Драган Матич', 'Желько Видокович', 'Яков Ковасевич'],
            nameRandomFemaleHelper: ['Велерия Марич', 'Злата Джукич', 'Марияна Новак', 'Татяна Хорват'],
            dollarEquivalent: '5,9 кун',
        },
        cz: {
            name: 'Чехия',
            code: 'cz',
            price: 790,
            oldPrice: 1580,
            labelPrice: 'крон',
            phoneHelper: 'Например +420 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Прага',
            cityRandomHelper: ['Прага', 'Брно', 'Теплице', 'Дарков', 'Карловы Вары', 'Гаррахов', 'Богемия'],
            nameRandomMaleHelper: ['Богуслав Витек', 'Лукаш Немец', 'Адам Ванек', 'Ростислав Нетрвал'],
            nameRandomFemaleHelper: ['Милослава Шмидова', 'Моника Бартова', 'Анета Краусова'],
            dollarEquivalent: '21 крон',
        },
        ch: {
            name: 'Швейцария',
            code: 'ch',
            price: 60,
            oldPrice: 120,
            labelPrice: 'фр.',
            phoneHelper: 'Например +41 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Стокгольм',
            cityRandomHelper: ['Стокгольм', 'Гётеборг', 'Мальмё', 'Уппсала', 'Вестерос', 'Эребру', 'Норрчёпинг'],
            nameRandomMaleHelper: ['Тобиас Линдберг', 'Гёста Виклунд', 'Нильс Бенгтссон', ' Стефан Гуннарссон'],
            nameRandomFemaleHelper: ['Анна Матссон', 'Карина Лунд', 'Линнея Сандстрём'],
            dollarEquivalent: '0,87 фр',
        },
        se: {
            name: 'Швеция',
            code: 'se',
            price: 490,
            oldPrice: 980,
            labelPrice: 'крон',
            phoneHelper: 'Например +46 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Stockholm',
            cityRandomHelper: ['Stockholm', 'Goeteborg', 'Malmoe', 'Uppsala', 'Kista', 'Vasteras', 'Orebro', 'Linkoping', 'Helsingborg', 'Huddinge'],
            nameRandomMaleHelper: ['Oscar Andersson', 'Lucas Johansson', 'William Karlsson', 'Liam Nilsson', 'Oliver Eriksson', 'Hugo', 'Alexander', 'Elias', 'Charlie', 'Noah'],
            nameRandomFemaleHelper: ['Alice Larsson', 'Lily Olsson', 'Maja Persson', 'Elsa Svensson', 'Ella Gustafsson', 'Alicia', 'Olivia', 'Ebba', 'Wilma'],
            dollarEquivalent: '7,8 крон',
        },
        ee: {
            name: 'Эстония',
            code: 'ee',
            price: 24,
            oldPrice: 48,
            labelPrice: 'евро',
            phoneHelper: 'Например +372 123456789',
            nameHelper: 'София Йуримаа',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Таллин',
            cityRandomHelper: ['Таллин', 'Тарту', 'Нарва', 'Пярну', 'Маарду', 'Валга', 'Кейла'],
            nameRandomMaleHelper: ['Ричард Тамм', 'Саамуэль Мяги', 'Расмус Ильвес'],
            nameRandomFemaleHelper: ['Герда Каск', 'Дорис Сепп', 'Лиия Ребане', 'Миральда Коппель'],
            dollarEquivalent: '0,8 евро',
        }
    };
})();